### ISSUE TITLE
Node 14: Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency

### ISSUE THREAD

**Issue by alcuadrado** [solidity-parser/parser#19]
When using this parser on Node 14, I get this warnings:

```
pato@pmbp:14% node --trace-warnings node_modules/.bin/buidler test
(node:2572) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object.<anonymous> (/private/tmp/14/node_modules/@solidity-parser/parser/dist/antlr4/RuleContext.js:32:46)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/private/tmp/14/node_modules/@solidity-parser/parser/dist/antlr4/PredictionContext.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
(node:2572) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object.<anonymous> (/private/tmp/14/node_modules/@solidity-parser/parser/dist/antlr4/tree/Trees.js:15:49)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/private/tmp/14/node_modules/@solidity-parser/parser/dist/antlr4/RuleContext.js:126:13)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
```

**Comment by fvictorio** [comment]
Thanks for reporting this! Seems to be a problem upstream: https://github.com/antlr/antlr4/issues/2834

**Comment by stfl** [comment]
I am seeing the same issue. when will this be fixed?

**Comment by fvictorio** [comment]
Hey @stfl, this depends on the fix for the linked antlr issue being published.

**Comment by chapati23** [comment]
FYI: Looks fixed in the upstream repo now!
https://github.com/antlr/antlr4/issues/2834#issuecomment-703337241

**Comment by fvictorio** [comment]
It seems like that change will be part of 4.9, which doesn't seem to be released.

**Comment by chapati23** [comment]
you're right, looks like we'll need for antlr@4.9 release
i just assumed it was already released

here's the 4.9 milestone link to track it: https://github.com/antlr/antlr4/milestone/20

**Comment by fvictorio** [comment]
Ok, I just used the unreleased version and it seems like it worked. But it was a HUGE change, so I published it under a rc for now. If someone wants to give it a try, `npm i @solidity-parser/parser@rc`. I tried it in prettier solidity and it worked fine.

cc @cgewecke @fernandomg

**Comment by prestwich** [comment]
An idea when we'll get an official release? With apple silicon, using v15.3.0 or later is now basically mandatory (due to [this issue](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/259))

**Comment by fvictorio** [comment]
@prestwich yes, `eth-gas-reporter` seems to be on `^0.8.2`, and I think I fixed this on a later version (don't remember exactly which one now).

cc @cgewecke

**Comment by cgewecke** [comment]
@fvictorio Ah! Thanks for the ping. Will fix rn.
