### ISSUE TITLE
Error Parse with BEP20Token.sol

### ISSUE THREAD

**Issue by hoangquochung95** [solidity-parser/parser#49]
Hi, 
I use solidity-parser to parse file BEP20Token.sol ( from [Binance](https://docs.binance.org/smart-chain/developer/BEP20Token.template) ) but I get an error 

My code: 

```
const parser = require("@solidity-parser/parser");
const fs = require("fs");

const input = fs.readFileSync("./BEP20Token.sol").toString();

try {
  const ast = parser.parse(input);
  console.log(ast)
} catch (e) {
  console.log(e);
  if (e instanceof parser.ParserError) {
    console.error(e.errors);
  }
}
```

```
TypeError: Cannot read property 'length' of undefined
    at ASTBuilder.visitExpression (D:\apps\test\testParse\node_modules\@solidity-parser\parser\dist\index.cjs.js:36002:26)
    at ASTBuilder.visitExpression (D:\apps\test\testParse\node_modules\@solidity-parser\parser\dist\index.cjs.js:36064:25)
    at ASTBuilder.visitExpressionStatement (D:\apps\test\testParse\node_modules\@solidity-parser\parser\dist\index.cjs.js:35932:24)
    at ExpressionStatementContext.accept (D:\apps\test\testParse\node_modules\@solidity-parser\parser\dist\index.cjs.js:33418:22)
    at ASTBuilder.visit (D:\apps\test\testParse\node_modules\@solidity-parser\parser\dist\index.cjs.js:17669:19)
    at ASTBuilder.visitSimpleStatement (D:\apps\test\testParse\node_modules\@solidity-parser\parser\dist\index.cjs.js:35449:17)
    at SimpleStatementContext.accept (D:\apps\test\testParse\node_modules\@solidity-parser\parser\dist\index.cjs.js:33590:22)
    at ASTBuilder.visit (D:\apps\test\testParse\node_modules\@solidity-parser\parser\dist\index.cjs.js:17669:19)
    at ASTBuilder.visitStatement (D:\apps\test\testParse\node_modules\@solidity-parser\parser\dist\index.cjs.js:35446:17)
    at D:\apps\test\testParse\node_modules\@solidity-parser\parser\dist\index.cjs.js:35482:51

```
Thanks

**Comment by hoangquochung95** [comment]
Sorry, file BEP20Token.sol have some variable need fill, It makes error
