### ISSUE TITLE
Can't handle stray commas in parameter list

### ISSUE THREAD

**Issue by axic** [solidity-parser/parser#56]
```solidity
contract C {
  function f(uint256 a,) external view {}
}
```

results in
```
$ prettier --write "contracts/**/*.sol"
contracts/a.sol
[error] contracts/a.sol: Error: Assertion error: unhandled type name case
[error]     at ASTBuilder.visitTypeName (/node_modules/@solidity-parser/parser/dist/index.cjs.js:35664:11)
[error]     at ASTBuilder.visitParameter (/node_modules/@solidity-parser/parser/dist/index.cjs.js:35499:22)
[error]     at ParameterContext.accept (/node_modules/@solidity-parser/parser/dist/index.cjs.js:32870:22)
[error]     at ASTBuilder.visit (/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
[error]     at /node_modules/@solidity-parser/parser/dist/index.cjs.js:35552:70
[error]     at Array.map (<anonymous>)
[error]     at ASTBuilder.visitFunctionDefinition (/node_modules/@solidity-parser/parser/dist/index.cjs.js:35552:54)
[error]     at FunctionDefinitionContext.accept (/node_modules/@solidity-parser/parser/dist/index.cjs.js:32561:22)
[error]     at ASTBuilder.visit (/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
[error]     at ASTBuilder.visitContractPart (/node_modules/@solidity-parser/parser/dist/index.cjs.js:35334:17)
```

The same happens with return parameters:
```solidity
contract C {
    function f(uint256) external view returns (uint256,) {}
}
```

I think there should be a nicer message saying what failed, if possible?

(*Originally opened at https://github.com/prettier-solidity/prettier-plugin-solidity/issues/585. Prettier uses the version 0.13.2 of the parser.*)

**Comment by fvictorio** [comment]
Hey @axic, thanks for reporting this.

Sadly, I don't think I'll be able to do this in the near future. More graceful error handling is way beyond my antlr knowledge, and I hope this package will eventually be replaced by slang's parser (which will have nice error handling as one of its goals). So I'm going to close this for bookkeeping, hope you don't mind!
