### ISSUE TITLE
Unbalanced parenthesis cause unclear error message

### ISSUE THREAD

**Issue by axic** [solidity-parser/parser#57]
```solidity
contract C {
  function f() {
    require(balanceOf();
  }
}
```

results in

```
[error] contracts/A.sol: TypeError: Cannot read property 'length' of undefined
[error]     at ASTBuilder.visitExpression (/node_modules/@solidity-parser/parser/dist/index.cjs.js:36002:26)
[error]     at ASTBuilder.visitExpressionStatement (/node_modules/@solidity-parser/parser/dist/index.cjs.js:35932:24)
[error]     at ExpressionStatementContext.accept (/node_modules/@solidity-parser/parser/dist/index.cjs.js:33418:22)
[error]     at ASTBuilder.visit (/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
[error]     at ASTBuilder.visitSimpleStatement (/node_modules/@solidity-parser/parser/dist/index.cjs.js:35449:17)
[error]     at SimpleStatementContext.accept (/node_modules/@solidity-parser/parser/dist/index.cjs.js:33590:22)
[error]     at ASTBuilder.visit (/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
[error]     at ASTBuilder.visitStatement (/node_modules/@solidity-parser/parser/dist/index.cjs.js:35446:17)
[error]     at /node_modules/@solidity-parser/parser/dist/index.cjs.js:35482:51
[error]     at Array.map (<anonymous>)
```

I think there should be a nicer message saying what failed, if possible?

(*Originally opened at https://github.com/prettier-solidity/prettier-plugin-solidity/issues/586. Prettier uses the version 0.13.2 of the parser.*)

**Comment by fvictorio** [comment]
See https://github.com/solidity-parser/parser/issues/56#issuecomment-1133412038
