### ISSUE TITLE
Unable to parse address[][] in abidecode()

### ISSUE THREAD

**Issue by zerosnacks** [solidity-parser/parser#66]
Whilst the Solidity compiler compiles this without errors the parser throws (both with Solhint and Prettier) on the following line:

```
(IUniswapV2Router02 uniswapV2Router, address[][] memory swapPaths) = abi.decode(strategyData, (IUniswapV2Router02, address[][]));
```

Context: https://github.com/Rari-Capital/fuse-v1/blob/15b3920fb017b3115b07362d7578d2df65f36582/src/liquidators/BalancerPoolTokenLiquidator.sol#L63

Error (on running Solhint):
```
/home/zerosnacks/Projects/fuse-v1/node_modules/solhint/lib/index.js:40
      throw e
      ^

Error: Unrecognized expression
    at ASTBuilder.visitExpression (/home/zerosnacks/Projects/fuse-v1/node_modules/@solidity-parser/parser/dist/index.cjs.js:36165:11)
    at ExpressionContext.accept (/home/zerosnacks/Projects/fuse-v1/node_modules/@solidity-parser/parser/dist/index.cjs.js:34066:22)
    at ASTBuilder.visit (/home/zerosnacks/Projects/fuse-v1/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
    at /home/zerosnacks/Projects/fuse-v1/node_modules/@solidity-parser/parser/dist/index.cjs.js:36301:19
    at Array.map (<anonymous>)
    at ASTBuilder.visitTupleExpression (/home/zerosnacks/Projects/fuse-v1/node_modules/@solidity-parser/parser/dist/index.cjs.js:36297:57)
    at TupleExpressionContext.accept (/home/zerosnacks/Projects/fuse-v1/node_modules/@solidity-parser/parser/dist/index.cjs.js:34972:22)
    at ASTBuilder.visit (/home/zerosnacks/Projects/fuse-v1/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
    at ASTBuilder.visitPrimaryExpression (/home/zerosnacks/Projects/fuse-v1/node_modules/@solidity-parser/parser/dist/index.cjs.js:36293:17)
    at ASTBuilder.visitExpression (/home/zerosnacks/Projects/fuse-v1/node_modules/@solidity-parser/parser/dist/index.cjs.js:36018:21)
```

**Comment by fvictorio** [comment]
Thank you, I'll try to get this fixed as soon as I have some time.

**Comment by zerosnacks** [comment]
Thanks! 😀
