### ISSUE TITLE
Assertion error: primary expression should exist when children length is 1

### ISSUE THREAD

**Issue by omurovec** [solidity-parser/parser#68]
After upgrading from `"0.13.2"` to `"0.14.2"` I receive the following error:

```
contracts/Perpetual.sol[error] contracts/Perpetual.sol: Error: Assertion error: primary expression should exist when children length is 1
[error]     at ASTBuilder.visitExpression (/Users/username/project/node_modules/@solidity-parser/parser/dist/index.cjs.js:36119:17)
[error]     at ASTBuilder.visitExpression (/Users/username/project/node_modules/@solidity-parser/parser/dist/index.cjs.js:36177:25)
[error]     at ASTBuilder.visitExpression (/Users/username/project/node_modules/@solidity-parser/parser/dist/index.cjs.js:36167:30)
[error]     at ASTBuilder.visitExpressionStatement (/Users/username/project/node_modules/@solidity-parser/parser/dist/index.cjs.js:36040:24)
[error]     at ExpressionStatementContext.accept (/Users/username/project/node_modules/@solidity-parser/parser/dist/index.cjs.js:33516:22)
[error]     at ASTBuilder.visit (/Users/username/project/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
[error]     at ASTBuilder.visitSimpleStatement (/Users/username/project/node_modules/@solidity-parser/parser/dist/index.cjs.js:35550:17)
[error]     at SimpleStatementContext.accept (/Users/username/project/node_modules/@solidity-parser/parser/dist/index.cjs.js:33688:22)
[error]     at ASTBuilder.visit (/Users/username/project/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
[error]     at ASTBuilder.visitStatement (/Users/username/project/node_modules/@solidity-parser/parser/dist/index.cjs.js:35547:17)
```

Tried looking for the error in `Perpetual.sol` but there's no given line numbers and couldn't find any info on this particular error anywhere.

**Comment by aoi-w** [comment]
@omurovec It would be difficult for developers to investigate the problem without a reproducible test case. Could you provide the copy of `contracts/Perpetual.sol`?

**Comment by fvictorio** [comment]
Closing for lack of reproduction steps.
