### ISSUE TITLE
ParserError: Could not instrument: ... extraneous input '....' expecting {';', '='} 

### ISSUE THREAD

**Issue by gitpusha** [solidity-parser/parser#9]
Hi, 

Like @fvictorio asked me to in[ this issue](https://github.com/sc-forks/solidity-coverage/issues/481#issuecomment-610658409) in the solidity-coverage repo, I opening the [same issue](https://github.com/sc-forks/solidity-coverage/issues/493) here:

First of all thank you for building and maintaining this tool.

I was trying to use the `solidity-coverage` buidler plugin for the first time, and I encountered this solidity-parser bug and some others which all seem to be related to `solc 0.6` syntax, I would assume.

An unexpected error occurred:
```
ParserError: Could not instrument: gelato_core/gelato_provider_module_examples/gelato_user_proxy_provider/ProviderModuleGelatoUserProxy.sol. (Please verify solc can compile this file without errors.) extraneous input 'isProxyExtcodehashProvided' expecting {';', '='} (17:45)
    at Object.parse (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-antlr/dist/index.js:79:11)
    at Instrumenter.instrument (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-coverage/lib/instrumenter.js:63:30)
    at API.instrument (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-coverage/lib/api.js:91:48)
    at SimpleTaskDefinition.action (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-coverage/plugins/buidler.plugin.js:86:23)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Environment._runTaskDefinition (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/@nomiclabs/buidler/src/internal/core/runtime-environment.ts:190:14)
    at main (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/@nomiclabs/buidler/src/internal/cli/cli.ts:151:5)
```

**This is the source solidity code referenced in the error log:**
FILE: ProviderModuleGelatoUserProxy.sol
LINE 17:  `mapping(bytes32 => bool) public override isProxyExtcodehashProvided;`

And all my contracts compile without errors using `npx buidler compile`.

**Comment by fvictorio** [comment]
This actually works with this parser, but I'm going to keep this issue open because the generated AST node doesn't indicate that the declaration has an override.

Question: do `override`s in variable declarations accept some possible "arguments" like overrides in method declarations? I guess not, but want to be 100% sure.

I mean, in function you can do `function foo() override (Base)`. Can you do that for state variables?

**Comment by fvictorio** [comment]
Ok, tested it out in remix and it seems is possible. Will work on this.

**Comment by gitpusha** [comment]
> Ok, tested it out in remix and it seems is possible. Will work on this.

Sorry I was late. But thank you for trying it out.

> This actually works with this parser, but I'm going to keep this issue open because the generated AST node doesn't indicate that the declaration has an override.

Sorry I am confused. Does this mean that the bug is somewhere else in the solidity-coverage tool, or can it be traced to the parser dependency, after all?

**Comment by cgewecke** [comment]
@gitpusha 

Going to switch Solidity-Coverage over to this parser today and will add your example to the unit tests. But it sounds like for the coverage tool's needs (which are quite coarse) this syntax will be ok.

**Comment by fvictorio** [comment]
Awesome! Let me know if there are other parser-related issues in solidity-coverage.

**Comment by gitpusha** [comment]
@fvictorio @cgewecke I thank you very much for your efforts! 

I am looking forward to generating my first solidity-coverage report!

@cgewecke I assume your update will also work for buidler `usePlugin("solidity-coverage")` since buidler does not use its own solidity-coverage dependency? So all I need to do is to upgrade the `solidity-coverage` package I have installed in my project and `npx buidler coverage --network coverage` should work?

**Comment by cgewecke** [comment]
@gitpusha Yes, correct.

**Comment by gitpusha** [comment]
@fvictorio and @cgewecke thanks for the update.

However, now I get a new Parser Error, I assume one of the following things could be the issue with my expressions in the contract (that compiles fine):

- `pragma experimental ABIEncoderV2` in order to accept solidity `structs` and `nested structs` as `function params` and to `emit` them in `events`.

- I am using solidity `try/catch` expressions

```
An unexpected error occurred:

Error: Could not instrument: gelato_core/GelatoCore.sol. (Please verify solc can compile this file without errors.) Unrecognized expression
    at ASTBuilder.Expression (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:758:11)
    at ASTBuilder.visit (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1304:38)
    at ASTBuilder.Expression (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:700:30)
    at ASTBuilder.visit (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1304:38)
    at ASTBuilder.TryStatement (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:483:24)
    at ASTBuilder.visit (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1304:38)
    at ASTBuilder.Statement (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:557:17)
    at ASTBuilder.visit (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1304:38)
    at ASTBuilder.<anonymous> (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1292:19)
    at Array.map (<anonymous>)
    at ASTBuilder.visit (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1291:16)
    at ASTBuilder.Block (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:517:24)
    at ASTBuilder.visit (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1304:38)
    at ASTBuilder.FunctionDefinition (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:143:20)
    at ASTBuilder.visit (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1304:38)
    at ASTBuilder.ContractPart (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:127:17)
    at ASTBuilder.visit (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1304:38)
    at ASTBuilder.<anonymous> (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1292:19)
    at Array.map (<anonymous>)
    at ASTBuilder.visit (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1291:16)
    at ASTBuilder.ContractDefinition (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:113:22)
    at ASTBuilder.visit (/Users/luis/Desktop/gelato-gnosis-safe/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1304:38)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
